### PR TITLE
French translation

### PR DESCRIPTION
**Pull request by foxted**
Hello!

Suggesting the French translation from the content I could find so far, I will try to keep an eye on new content to translate it in the future.

### CODE REVIEW

**Comment by mattstauffer** [comment]
Thanks @foxted! I think we need to add a few other pieces here? Would you check it against this guide?

https://github.com/tightenco/onramp/blob/master/translation-guide.md

**Comment by foxted** [comment]
I am missing one piece indeed! I will add that today or tomorrow :)

**Comment by foxted** [comment]
This should be ready to go, sorry for the delay.

**Comment by mattstauffer** [comment]
Thanks @foxted!

**Pull request merged**
