### PR TITLE
Add contributing document (closes #80)

### LINKED ISSUE #80: readme.md and contributing.md could include more info about getting started
There was chat elsewhere today about things like:

* What is on different branches of this repo?
* How PR's work
* Which livestream videos should I watch? All of them? The latest?
* Details of the database seeding

And I have my own questions about exactly what this repo is and if/how I can contribute.

I'll copy some conversation below for reference.

My reaction was to pop in here and see what the readme and contrinuting.md say, and that lead me to opening this issue to try and improve those documents.

@mattstauffer said: 

> one of the things i think would be really cool is if we can make this not only super easy for new folks to use, but also super easy for them to contribute to, AND we can maybe even use it and its readme/contributing.md/etc. as examples of how to make open source laravel projects friendly to new folks

So let's do that. I'll try and start making some improvements to the docs over the next couple of days. But feel free to chip in if I can't.

## Relevant extracts/questions

> How do the migrations/seeding work?

`php artisan migrate:fresh —seed`

> What IS the mes/database-backed-learning branch? Which should I use if contributing?

??? - need a general overview of branches - presumably this is explained in the videos?

> How do PR's work with merging? (This started as a question along the lines of: "If I fork the repo and work on the master, then create a PR with my changes, won't it create conflicts if it's merged after other changes on master?")

Probably need to point off to another resource on "How to PR with Git/GitHub". This is old and JavaScripty, but may be a helpful 38 mins of free (I think!) video: https://egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github

### PR DESCRIPTION
**Pull request by Treggats**
Implements the contributing.md part of issue #80 

[X] add artisan key generate

### CODE REVIEW

**Comment by wotta** [comment]
@Treggats what is the status of this draft?
You could split the document up in some smaller bits so the main part of the contributing file is being committed.

**Comment by mattstauffer** [comment]
@Treggats Re-up on the question--if you can't finish this please let me know and I'll take it over. Thanks!

**Comment by Treggats** [comment]
I have a bunch almost ready to go. Need to finish it up and Ill update the
PR

Op do 7 nov. 2019 15:30 schreef Matt Stauffer <notifications@github.com>:

**Comment by Treggats** [comment]
@mattstauffer this one is ready for review.

I've let the 'contribute to onramp' alone on purpose, since it has changed a lot.
Maybe you or someone else can pick this up.

**Comment by mattstauffer** [comment]
Thanks @Treggats!

**Pull request merged**
