### PR TITLE
Translation for Indonesian Language 🇮🇩

### PR DESCRIPTION
**Pull request by rizkyarlin**

### CODE REVIEW

**Comment by mattstauffer** [comment]
Thanks @rizkyarlin!!

**Comment by mattstauffer** [comment]
@rizkyarlin Is there any shorter name we could use?

image

**Comment by rizkyarlin** [comment]
The official name of Indonesian language is "Bahasa Indonesia". People sometimes just use "Bahasa", but it translates to "Language" which is incorrect.

I'm gonna change it to bahasa and after that I'll try to make a PR to make the font size smaller for a long  Language name such as mine.

**Comment by mattstauffer** [comment]
@rizkyarlin Ahh, thanks for the clarification; and I agree that would be super helpful on the re-size. Thanks!

**Pull request merged**
