### PR TITLE
Adds Portuguese (Portugal) translation files for authentication, validation and pagination

### PR DESCRIPTION
**Pull request by joseborges**
Adds missing translations for Portuguese language on:

learn.pt.php (still in english, until team decision about translation of contents)
pt.json
lang/pt/auth.php
lang/pt/pagination.php
lang/pt/passwords.php
lang/pt/validation.php

### CODE REVIEW

**Comment by mattstauffer** [comment]
Thanks! This won't work until we either A) allow for translation without unique resources files, or B) add a `learn.pt.php` file. Additionally, it breaks the UI. Thankfully, that UI break was fixed in #68, but that's still on the `mes/database-backed-learning` branch, so I'm going to hold on this PR until we merge that one in. Thanks for your work!

**Comment by mattstauffer** [comment]
image
image

**Comment by joseborges** [comment]
Will work on that learn.ptphp right away

**Comment by mattstauffer** [comment]
Closed because #71

**Pull request closed without merging**
