### PR TITLE
Store preferred language for resources (closes #93)

### LINKED ISSUE #93: Store the preferred way to show resources
As discussed in the stream yesterday.

We currently have no way to know what the preferred way of a user is to view the resources (in what locale)

Currently we have three options
- Only current
- Only English
- English and current

These options need to be stored if a user is logged in in something like a preference table for the user.

### PR DESCRIPTION
**Pull request by Treggats**
implements issue #93

### CODE REVIEW

**Comment by mattstauffer** [comment]
Please make sure to keep the preference toggle on the module page. And have it save the preference in the session or cookie so llit works for not logged in users

**Comment by Treggats** [comment]
@jonsugar commented that the following would be a good idea

>>> We can keep the preferences page. That's fine. I'm saying we make the filter into a vue component. On the blade side it has access to the user object. It will set up the filter acording to their preference. But if the user changes the preferece in the filter then the component posts to your controller. Page then refreshes.

**Comment by Treggats** [comment]
@jonsugar feel free to chip in, I'm not super fluent in Vue and not 100% sure how to build this.

**Comment by mattstauffer** [comment]
Replaced by #103 (because I wanted to be able to contribute code to it)

**Pull request closed without merging**
